export type TextColorType =
  | 'text-white'
  | 'text-primary'
  | 'text-secondary'
  | 'text-tertiary'
  | 'text-placeholder'
  | 'text-disabled'
  | 'text-brand'
  | 'text-link'
  | 'text-link-hover'
  | 'text-notice'
  | 'text-success'
  | 'text-warning'
  | 'text-error';
export type FontType =
  | 'display-large'
  | 'display-small'
  | 'heading-large'
  | 'heading-medium'
  | 'heading-small'
  | 'body-large'
  | 'body-medium'
  | 'body-small'
  | 'label-large'
  | 'label-medium'
  | 'label-small'
  | 'caption-medium'
  | 'caption-small';
export type IconType =
  | 'calendar'
  | 'home'
  | 'pencil'
  | 'people'
  | 'people-stroke'
  | 'crown'
  | 'sound'
  | 'chat'
  | 'send'
  | 'alarm'
  | 'arrow'
  | 'upload'
  | 'grab'
  | 'theme'
  | 'search'
  | 'cross'
  | 'error'
  | 'warning'
  | 'success'
  | 'leave';
export type SocialIconType = 'kakao' | 'naver' | 'google';
export type IconSizeType = '16' | '20' | '24' | '28' | '40' | '80';
