/**
 * API 에러 코드 상수
 */
export const ERROR_CODES = {
  // 일반 에러
  CONCURRENT_MODIFICATION_EXCEPTION: 'CONCURRENT_MODIFICATION_EXCEPTION',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  NOT_SUPPORTED_EXTENSION: 'NOT_SUPPORTED_EXTENSION',

  // 인증 관련 에러
  JWT_NOT_VALID: 'JWT_NOT_VALID',
  JWT_NOT_FOUND_IN_HEADER: 'JWT_NOT_FOUND_IN_HEADER',
  JWT_NOT_FOUND_IN_COOKIE: 'JWT_NOT_FOUND_IN_COOKIE',
  TOKEN_HIJACKED: 'TOKEN_HIJACKED',
  REGISTRATION_TOKEN_NOT_FOUND: 'REGISTRATION_TOKEN_NOT_FOUND',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',

  // 사용자 관련 에러
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  NICKNAME_DUPLICATED: 'NICKNAME_DUPLICATED',
  INVALID_NICKNAME: 'INVALID_NICKNAME',

  // 크루 관련 에러
  CREW_NOT_FOUND: 'CREW_NOT_FOUND',
  LEADER_CANNOT_EXPEL: 'LEADER_CANNOT_EXPEL',
  LEADER_PERMISSION_DENIED: 'LEADER_PERMISSION_DENIED',
  CREW_JOIN_INFO_NOT_FOUND: 'CREW_JOIN_INFO_NOT_FOUND',
  ALREADY_JOINED_CREW: 'ALREADY_JOINED_CREW',
  CREW_MEMBERSHIP_REQUIRED: 'CREW_MEMBERSHIP_REQUIRED',
  INVALID_CREW_CAPACITY: 'INVALID_CREW_CAPACITY',

  // 초대 관련 에러
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',

  // 모먼트 관련 에러
  MOMENT_NOT_FOUND: 'MOMENT_NOT_FOUND',
  INVALID_MOMENT_CAPACITY: 'INVALID_MOMENT_CAPACITY',
  INVALID_MOMENT_DATE: 'INVALID_MOMENT_DATE',
  ALREADY_JOINED_MOMENT: 'ALREADY_JOINED_MOMENT',
  MOMENT_DEADLINE_EXPIRED: 'MOMENT_DEADLINE_EXPIRED',
  MOMENT_CAPACITY_FULL: 'MOMENT_CAPACITY_FULL',
  MOMENT_PARTICIPATION_NOT_FOUND: 'MOMENT_PARTICIPATION_NOT_FOUND',
  LOCATION_LIMIT_EXCEEDED: 'LOCATION_LIMIT_EXCEEDED',
} as const;
